MAPEO_SECTORES_INDUSTRY = {"agencies":"Government",
    "agency_mbs":"Government",
    "utilities":"Utilities",
    "home_builders_&_real_estate":"Real Estate",
    "property":"Real Estate",
    "real_estate":"Real Estate",
    "real_estate_/_homebuilders_/_building_materials":"Real Estate",
    "real_estate_investment_trusts":"Real Estate",
    "reits_&_real_estate":"Real Estate",  
    "other_products":"Otros",
    "other_securitized":"Otros",
    "others":"Otros",
    "Other":"Otros",
    "services":"Otros",
    "supranationals":"Otros",
    "basic_materials":"Materials",
    "building_materials":"Materials",
    "chemicals":"Materials",
    "materials":"Materials",
    "metals_&_mining":"Materials",
    "oil_&_gas":"Materials",
    "consumer_goods":"Main Consumer Goods",
    "consumer_goods_(cyclical)":"Main Consumer Goods",
    "consumer_goods_(non_cyclical)":"Main Consumer Goods",
    "food":"Main Consumer Goods",
    "retail":"Main Consumer Goods",
    "information_technology":"Information Technology",
    "technology":"Information Technology",
    "technology_&_electronic":"Information Technology",
    "technology_&_electronics":"Information Technology",
    "water_technology":"Information Technology",
    "basic_industries":"Industrials",
    "gold":"Industrials",
    "industrials":"Industrials",
    "infrastructure":"Industrials",
    "transportation":"Industrials",
    "health_care":"Health Care",
    "health_care,_education_&_childcare":"Health Care",
    "health_care_&_pharmaceuticals":"Health Care",
    "health_care_&_social_services":"Health Care",
    "health_care_services":"Health Care",
    "health_services":"Health Care",
    "healthcare":"Health Care",
    "agency_mortgage":"Government",
    "government":"Government",
    "government_debt_(external)":"Government",
    "government_related":"Government",
    "municipals":"Government",
    "us_agencies":"Government",
    "us_investment_grade_credit":"Government",
    "us_treasuries/agencies":"Government",
    "us_treasury":"Government",
    "asset_backed_securities":"Financials",
    "bank_loans":"Financials",
    "banks":"Financials",
    "bonds_(covered)":"Financials",
    "capital_goods":"Financials",
    "cash":"Financials",
    "cash_&_cash_equivalents":"Financials",
    "clo_securities":"Financials",
    "collateralized_debt_obligations":"Financials",
    "collateralized_loan_obligations":"Financials",
    "commercial_mortgage_backed_securities":"Financials",
    "commercial_mortgages":"Financials",
    "corporates":"Financials",
    "corporates_(industrials)":"Financials",
    "corporates_(investment_grade)":"Financials",
    "corporates_ig":"Financials",
    "derivatives_&_cash":"Financials",
    "diversified_financials":"Financials",
    "emd_hard_currency":"Financials",
    "emd_local_currency":"Financials",
    "emerging_market_debt":"Financials",
    "emerging_markets":"Financials",
    "equities":"Financials",
    "finance":"Financials",
    "finance_&_investment":"Financials",
    "financial":"Financials",
    "financial_companies":"Financials",
    "financial_company_commer...":"Financials",
    "financial_institutions":"Financials",
    "financial_institutions_(other)":"Financials",
    "financial_services":"Financials",
    "financials":"Financials",
    "financials_&_investment_companies":"Financials",
    "financials_&_investments":"Financials",
    "financials_(incl._deposits)":"Financials",
    "high_yield_corporates":"Financials",
    "hy_corporate":"Financials",
    "insurance":"Financials",
    "local":"Financials",
    "local_curr._govt/agency_bonds_(investment_grade)":"Financials",
    "local_curr._govt/agency_bonds_(non_inv_grade)":"Financials",
    "mortgage_backed_securities":"Financials",
    "non-agency_mortgage":"Financials",
    "non-local_curr._sovereign_bonds_(non_inv_grade)":"Financials",
    "non-us_credit":"Financials",
    "non_classified_equity":"Financials",
    "non_corporate_credit":"Financials",
    "sovereigns":"Financials",
    "energy":"Energy",
    "energy_efficiency":"Energy",
    "consumer_staples":"Consumer Staples",
    "consumer_(non_cyclical)":"Consumer Non Cyclical",
    "consumer_non-cyclical":"Consumer Non Cyclical",
    "consumer_non-cyclicals":"Consumer Non Cyclical",
    "consumer_discretionary":"Consumer Discretionary",
    "consumer_services":"Consumer Discretionary",
    "consumer_(cyclical)":"Consumer Cyclical",
    "consumer_cyclical":"Consumer Cyclical",
    "consumer_cyclicals":"Consumer Cyclical",
    "communic_services":"Communication Services",
    "communication":"Communication Services",
    "communication_services":"Communication Services",
    "communications":"Communication Services",
    "communications_&_media":"Communication Services",
    "technology,_media_&_telecommunications":"Communication Services",
    "telecommunication_services":"Communication Services",
    "telecommunications":"Communication Services",
    "telecommunications_services":"Communication Services",
    "food,_beverage_&_tobacco":"Main Consumer Goods",
    "global_governments":"Government",
    "health_care_equipment_&_supplies":"Health Care",
    "household_products":"Main Consumer Goods",
    "information_&_communication":"Information Technology",
    "interactive_media_&_services":"Information Technology",
    "internet_&_direct_marketing_retail":"Information Technology",
    "it_services":"Information Technology",
    "local_govt_debt":"Financials",
    "machinery":"Industrials",
    "pharmaceuticals":"Health Care",
    "pharmaceuticals,_biotechnology_&_life_sciences":"Health Care",
    "retail_trade":"Main Consumer Goods",
    "semiconductors_&_semiconductor_equipment":"Industrials",
    "software":"Information Technology",
    "software_&_services":"Information Technology",
    "textiles,_apparel_&_luxury_goods":"Industrials",
    "transportation_equipment":"Industrials",
    "us_high_yield_credit":"Government",
    "us_interest_rate_derivatives":"Government",
    "wholesale_trade":"Industrials",
    "abs":"Otros",
    "absolute_return_(non_us)":"Otros",
    "absolute_return_(us)":"Otros",
    "additional_tier_1":"Otros",
    "agency":"Otros",
    "agency_arms":"Otros",
    "agency_debentures":"Otros",
    "agency_mortgage_backed_securities":"Otros",
    "agency_pass-through_mbs":"Otros",
    "agency_residential_mortg...":"Otros",
    "agency_rmbs":"Otros",
    "agriculture":"Otros",
    "air_transportation":"Otros",
    "airport_services":"Otros",
    "airports":"Otros",
    "appropriation":"Otros",
    "asset_back_-_/_mortgage_back_securities":"Otros",
    "asset_backed_bonds":"Otros",
    "asset_backed_commercial_...":"Otros",
    "auto_manufacturers":"Otros",
    "automation":"Otros",
    "automobiles":"Otros",
    "automobiles_&_auto_parts":"Otros",
    "automobiles_&_equipment_suppliers":"Otros",
    "automotive":"Otros",
    "availabilities_&_invested_liquidities":"Otros",
    "bank_instruments":"Otros",
    "banking":"Otros",
    "banking_activities":"Otros",
    "banks_&_brokers":"Otros",
    "banks_&_credit_institutions":"Otros",
    "basic_trade":"Otros",
    "bond_futures":"Otros",
    "broadcasting":"Otros",
    "broadcasting_&_entertainment":"Otros",
    "brokerage":"Otros",
    "brokerage,_managers_assets_and_stock_exchanges":"Otros",
    "building_mat._&_home_const.":"Otros",
    "business_equipment_&_services":"Otros",
    "cable":"Otros",
    "cable-operators":"Otros",
    "cable_&_satellite":"Otros",
    "cable_&_satellite_television":"Otros",
    "cable_operators":"Otros",
    "cash_&_derivatives":"Otros",
    "cash_&_equivalent":"Otros",
    "cash_&_other_assets_less_liabilities":"Otros",
    "cash_&_others":"Otros",
    "cash_&_time_deposit":"Otros",
    "cash_(incl_futures)":"Otros",
    "cash_+_forwards":"Otros",
    "cash_deposits":"Otros",
    "cash_equivalents":"Otros",
    "cdx":"Otros",
    "certificates_of_deposit":"Otros",
    "chemicals,_plastics_&_rubber":"Otros",
    "chemicals_and_plastics":"Otros",
    "cmbs_(non_us)":"Otros",
    "cmbs_(non_us_agency)":"Otros",
    "cmbs_(us_agency)":"Otros",
    "cmos_(us_agency)":"Otros",
    "collateralized":"Otros",
    "collateralized_loan_obligation":"Otros",
    "collateralized_mortgage_bonds":"Otros",
    "collateralized_mortgage_obligations":"Otros",
    "commercial_deposits":"Otros",
    "commercial_mbs":"Otros",
    "commercial_paper/cash":"Otros",
    "commercial_papers":"Otros",
    "commercial_papers_&_notes":"Otros",
    "commercial_services":"Otros",
    "computer_hardware_&_network":"Otros",
    "cons/comm/lease_financing":"Otros",
    "construction":"Otros",
    "construction_&_engineering":"Otros",
    "construction_machinery":"Otros",
    "consumer":"Otros",
    "consumer_&_services_application":"Otros",
    "consumer_goods_&_services_(non_cyclical)":"Otros",
    "consumer_goods_(durable)":"Otros",
    "consumer_goods_(non_durables)":"Otros",
    "consumer_products":"Otros",
    "consumer_products_/_services":"Otros",
    "containers":"Otros",
    "convertible_bonds":"Otros",
    "convertibles":"Otros",
    "corporate":"Otros",
    "corporate_(cyclical)":"Otros",
    "corporate_(high_yield":"Otros",
    "corporate_(investment_grade)":"Otros",
    "corporate_(non_cyclical)":"Otros",
    "corporate_(utilities)":"Otros",
    "corporate_-_financials":"Otros",
    "corporate_-_utilities":"Otros",
    "corporate_bonds":"Otros",
    "corporate_bonds_(investment_grade)":"Otros",
    "corporate_bonds_(non_investment_grade)":"Otros",
    "corporate_bonds_(speculative_debt)":"Otros",
    "corporates_(financial_institutions)":"Otros",
    "corporates_(financials)":"Otros",
    "corporates_(utilities)":"Otros",
    "corporates_hy":"Otros",
    "cosmetics":"Otros",
    "covered":"Otros",
    "covered_bonds_and":"Otros",
    "credit_(investment_grade)":"Otros",
    "credit_baskets":"Otros",
    "credit_default_swap_index":"Otros",
    "credit_default_swaps":"Otros",
    "currencies":"Otros",
    "cyclical_services":"Otros",
    "dedicated_tax":"Otros",
    "derivatives":"Otros",
    "derivatives:_currency_derivatives":"Otros",
    "derivatives:_derivatives":"Otros",
    "discount_note":"Otros",
    "distribution":"Otros",
    "diversified":"Otros",
    "diversified_&_conglomerate_services":"Otros",
    "diversified_financial_services":"Otros",
    "diversified_holding_companies":"Otros",
    "diversified_manufacturing":"Otros",
    "diversified_media":"Otros",
    "dm_government_agencies":"Otros",
    "dm_sovereign_debt":"Otros",
    "duration_instruments_net_other_short":"Otros",
    "education_&_civic_organizations":"Otros",
    "electric":"Otros",
    "electric_utilities":"Otros",
    "electricity":"Otros",
    "electricity_&_technology":"Otros",
    "electronics":"Otros",
    "electronics_&_semiconductors":"Otros",
    "em_corporate":"Otros",
    "em_external":"Otros",
    "em_government":"Otros",
    "em_government_agencies":"Otros",
    "em_hard_currency_corporate_debt":"Otros",
    "em_hard_currency_quasi_sovereign_debt":"Otros",
    "em_hard_currency_sovereign_debt":"Otros",
    "em_local":"Otros",
    "em_local_currency":"Otros",
    "em_local_currency_sovereign_debt":"Otros",
    "emd_corporate":"Otros",
    "emd_sovereign":"Otros",
    "emerging_market_bonds":"Otros",
    "emerging_market_corporate":"Otros",
    "emerging_market_corporates":"Otros",
    "emerging_market_hard_currency_debt":"Otros",
    "emerging_market_irs":"Otros",
    "emerging_markets_-_investment_grade":"Otros",
    "emerging_markets_-_sovereigns":"Otros",
    "emerging_markets_corporates":"Otros",
    "emu":"Otros",
    "enabling_infrastructure":"Otros",
    "enabling_technologies":"Otros",
    "enabling_technology":"Otros",
    "energy_&_water_supply":"Otros",
    "energy_-_midstream":"Otros",
    "energy_-_upstream":"Otros",
    "engineering":"Otros",
    "entertainment_&_leisure":"Otros",
    "entreprise":"Otros",
    "environmental_services":"Otros",
    "equipment_goods":"Otros",
    "eur/uk_corporate":"Otros",
    "eur/uk_high_yield":"Otros",
    "euro_bonds":"Otros",
    "exchange_traded_funds":"Otros",
    "external_sovereign_credit":"Otros",
    "federal_governments_bonds":"Otros",
    "floating_rate":"Otros",
    "floating_rate_instruments":"Otros",
    "floating_rate_notes":"Otros",
    "food_&_beverage":"Otros",
    "food_&_drug_retailers":"Otros",
    "food_&_tobacco":"Otros",
    "foreign_agencies":"Otros",
    "foreign_exchange":"Otros",
    "foreign_sovereigns":"Otros",
    "forward_contracts":"Otros",
    "free_time":"Otros",
    "funds":"Otros",
    "futures":"Otros",
    "fx_&_cash":"Otros",
    "gambling_&_leisure":"Otros",
    "gaming":"Otros",
    "gaming_&_lodging_&_leisure":"Otros",
    "gaming_/_lodging_/_leisure":"Otros",
    "gaming_lodging_&_leisure":"Otros",
    "gas_distribution":"Otros",
    "gas_utilities":"Otros",
    "global_credit_(investment_grade)":"Otros",
    "government_&_agencies":"Otros",
    "government_&_agencies_(investment_grade)":"Otros",
    "government_&_government_guaranteed_bonds":"Otros",
    "government_bonds":"Otros",
    "government_bonds_(inflation_linked)":"Otros",
    "government_guaranteed":"Otros",
    "government_related_(agencies)":"Otros",
    "government_related_(local_authority)":"Otros",
    "government_related_(sovereign)":"Otros",
    "government_related_(supranationals)":"Otros",
    "government_sovereign_agency":"Otros",
    "governments":"Otros",
    "hard_currency_(em)":"Otros",
    "hc_corp":"Otros",
    "healthcare_&_pharm.":"Otros",
    "high_grade_corporates":"Otros",
    "high_yield":"Otros",
    "high_yield_credit":"Otros",
    "higher_education":"Otros",
    "highways/railtracks":"Otros",
    "home_construction":"Otros",
    "hospitals":"Otros",
    "hotels":"Otros",
    "housing_&_multifamily":"Otros",
    "ig_corp":"Otros",
    "ig_corporate":"Otros",
    "independent":"Otros",
    "independent_e&p":"Otros",
    "industrial":"Otros",
    "industrial_development_&_pollution_control_revenue":"Otros",
    "industrial_products":"Otros",
    "industrials_&_business_services":"Otros",
    "industry":"Otros",
    "industry,_other":"Otros",
    "inflation_linked":"Otros",
    "inflation_linked_securities":"Otros",
    "information_techn":"Otros",
    "insight_emd_fund":"Otros",
    "insurance_companies":"Otros",
    "insurance_linked_securities":"Otros",
    "integrated":"Otros",
    "integrated_oil":"Otros",
    "interest_rate_derivatives":"Otros",
    "internet_software_&_it_services":"Otros",
    "investment_&_benefit_funds":"Otros",
    "investment_companies":"Otros",
    "investment_grade_credit":"Otros",
    "investment_grade_industrials":"Otros",
    "it_security":"Otros",
    "lc_corp":"Otros",
    "leisure":"Otros",
    "liquid_assets":"Otros",
    "liquidities":"Otros",
    "loan_securities":"Otros",
    "local_authorities":"Otros",
    "local_debt":"Otros",
    "local_emerging_market":"Otros",
    "local_government":"Otros",
    "local_government_debt":"Otros",
    "local_governments_-_provincial_bonds":"Otros",
    "long_term_care":"Otros",
    "luxury":"Otros",
    "manufacturing":"Otros",
    "media":"Otros",
    "media_&_entertainment":"Otros",
    "media_&_services":"Otros",
    "media_-_cable":"Otros",
    "media_cable":"Otros",
    "metals":"Otros",
    "miscellaneous_consumer_goods":"Otros",
    "mortgage_backed":"Otros",
    "mortgage_backed_security_pass-through":"Otros",
    "mortgage_pass_thrus":"Otros",
    "mortgage_securities":"Otros",
    "multi_utilities":"Otros",
    "municipal/otherã£âžã¢â€â":"Otros",
    "municipal_&_foreign_city_bonds":"Otros",
    "municipal_bonds":"Otros",
    "municipalities":"Otros",
    "municipals_us":"Otros",
    "mutual_funds":"Otros",
    "natural_gas":"Otros",
    "net_liquid_assets":"Otros",
    "net_other_short":"Otros",
    "non-local_curr._sovereign_bonds_(investment_grade)":"Otros",
    "non-us_developed_bonds":"Otros",
    "non-us_govt/agency":"Otros",
    "non-us_hy_corp":"Otros",
    "non-us_sovereign":"Otros",
    "non-usd_developed":"Otros",
    "non_agency_mbs":"Otros",
    "non_agency_rmbs":"Otros",
    "non_agency_rmbs_us":"Otros",
    "non_corporates":"Otros",
    "non_credit":"Otros",
    "non_us_sovereigns":"Otros",
    "north_america":"Otros",
    "not_classified":"Otros",
    "not_classified_-_non_equity":"Otros",
    "oil,_gas_&_consumable_fuels":"Otros",
    "oil_&_gas_storage_&_transportation":"Otros",
    "oil_refining_&_marketing":"Otros",
    "other_energy":"Otros",
    "other_industrials":"Otros",
    "other_revenue":"Otros",
    "other_sectors":"Otros",
    "other_securities":"Otros",
    "otherã£âžã¢â€â":"Otros",
    "overnight_&_repo":"Otros",
    "owned_no_guarantee":"Otros",
    "packaging":"Otros",
    "packaging_&_containers":"Otros",
    "pass-through_(us_agency)":"Otros",
    "pass_through_mbs":"Otros",
    "petroleum":"Otros",
    "pharmaceuticals,_cosmetics_&_medical_products":"Otros",
    "physical_gold":"Otros",
    "physical_securities":"Otros",
    "pipelines":"Otros",
    "power":"Otros",
    "public_&_non_profit_institutions":"Otros",
    "public_power":"Otros",
    "public_services":"Otros",
    "public_utilities":"Otros",
    "publishing":"Otros",
    "pulp_&_paper":"Otros",
    "quasi":"Otros",
    "quasi,_sovereigns,_supranationals_&_agencies":"Otros",
    "quasi_&_foreign_government":"Otros",
    "quasi_-_corporates":"Otros",
    "quasi_-_sovereigns":"Otros",
    "quasi_government_bonds":"Otros",
    "quasi_government_debt":"Otros",
    "quasi_sovereigns":"Otros",
    "quasigovernment":"Otros",
    "rail_transportation":"Otros",
    "reits":"Otros",
    "renewables":"Otros",
    "repos":"Otros",
    "repurchase_agreements":"Otros",
    "residential_mortgage_backed_securities":"Otros",
    "retailers_&_restaurants":"Otros",
    "retailing":"Otros",
    "rmbs":"Otros",
    "rmbs_(non_us)":"Otros",
    "securitized":"Otros",
    "securitized_assets":"Otros",
    "security_services":"Otros",
    "senior":"Otros",
    "sovereign":"Otros",
    "sovereign_bonds_(investment_grade)":"Otros",
    "sovereign_bonds_(speculative_debt)":"Otros",
    "sovereign_related_(ex_us)":"Otros",
    "sovereigns_(ex_us)":"Otros",
    "sport":"Otros",
    "staples_services":"Otros",
    "structured":"Otros",
    "sub_sovereign":"Otros",
    "super_retail":"Otros",
    "suppliers":"Otros",
    "support_-_services":"Otros",
    "supranational":"Otros",
    "supranational,_sub-sovereign_&_agency_paper":"Otros",
    "supranational_organizations":"Otros",
    "supranationales":"Otros",
    "swaps":"Otros",
    "tax_obligations_&_general":"Otros",
    "tax_obligations_limited":"Otros",
    "telecom_tower_reits":"Otros",
    "term_deposits":"Otros",
    "textiles":"Otros",
    "tier_1_&_preferred":"Otros",
    "tier_2":"Otros",
    "tier_2_coco":"Otros",
    "traffic_&_transportation":"Otros",
    "transportation_(ex_air_&_railway)":"Otros",
    "travel_&_tourism":"Otros",
    "treasuries":"Otros",
    "treasuries_&_treasury_futures":"Otros",
    "treasury":"Otros",
    "treasury_&_govt_related":"Otros",
    "treasury_bills":"Otros",
    "treasury_notes_&_bills":"Otros",
    "treasury_repurchase_agreements":"Otros",
    "u.s._government_agency_r...":"Otros",
    "u.s._govt_&_agency_securities":"Otros",
    "ucits":"Otros",
    "uk":"Otros",
    "unclassified":"Otros",
    "unidentified":"Otros",
    "unit_trusts":"Otros",
    "unknown":"Otros",
    "unknown_sector":"Otros",
    "us_convertibles":"Otros",
    "us_corporates":"Otros",
    "us_government_agencies":"Otros",
    "us_government_related":"Otros",
    "us_high_yield":"Otros",
    "us_treasury_debt":"Otros",
    "utility":"Otros",
    "water_&_sewer":"Otros",
    "water_supply":"Otros",
    "water_utilities":"Otros",
    "wired":"Otros",
    "wireless":"Otros",
    "wirelines":"Otros",
    "investment_grade_financials":"Otros",
    "investments_&_misc_financial_services":"Otros",
    "non-financials":"Otros",
    "non_captive_consumer_finance":"Otros",
    "non_captive_diversified_finance":"Otros",
    "other_financials":"Otros",   
    "other":"Otros"  
  }