MAPEO_SECTORES_INDUSTRY = {
    'Tax Obligations Limited': 'Government',
    'Transportation': 'Otros',
    'Education & Civic Organizations': 'Consumer Staples',
    'Health Care': 'Health Care',
    'Tax Obligations & General': 'Government',
    'Utilities': 'Otros',
    'Water & Sewer': 'Utilities',
    'Housing & Multifamily': 'Otros',
    'Long Term Care': 'Otros',
    'Consumer Discretionary': 'Consumer Discretionary',
    'TECHNOLOGY': 'Otros',
    'FINANCIALS': 'Otros',
    'CONSUMER CYCLICALS': 'Main Consumer Goods',
    'BASIC MATERIALS': 'Otros',
    'INDUSTRIALS': 'Otros',
    'CONSUMER NON-CYCLICALS': 'Main Consumer Goods',
    'ENERGY': 'Energy',
    'HEALTHCARE': 'Health Care',
    'UTILITIES': 'Otros',
    'NOT CLASSIFIED - NON EQUITY': 'Financials',
    'NON CLASSIFIED EQUITY': 'Financials',
    'Information Technology': 'Otros',
    'Financials': 'Otros',
    'Communication Services': 'Communication Services',
    'Industrials': 'Otros',
    'Materials': 'Otros',
    'Others': 'Otros',
    'Consumer Staples': 'Main Consumer Goods',
    'Cash & Cash Equivalents': 'Otros',
    'Energy': 'Energy',
    'Building': 'Industrials',
    'Media Non Cable': 'Communication Services',
    'Cable & Satellite': 'Communication Services',
    'Technology': 'Otros',
    'Cash': 'Otros',
    'Financial Companies': 'Otros',
    'Consumer Goods (Non Cyclical)': 'Consumer Staples',
    'Consumer Goods (Cyclical)': 'Consumer Discretionary',
    'Capital Goods': 'Industrials',
    'Brokerage': 'Otros',
    'Communications': 'Otros',
    'Basic Industries': 'Otros',
    'REITs & Real Estate': 'Real Estate',
    'REAL ESTATE': 'Real Estate',
    'Services': 'Otros',
    'Broadcasting': 'Communication Services',
    'Gambling & Leisure': 'Consumer Discretionary',
    'Manufacturing': 'Otros',
    'Retailing': 'Otros',
    'Food & Tobacco': 'Consumer Staples',
    'Securitized': 'Otros',
    'US Government Related': 'Government',
    'Credit (Investment Grade)': 'Financials',
    'Non-Usd Developed': 'Otros',
    'Emerging Markets': 'Otros',
    'High Yield Credit': 'Financials',
    'Net Other Short Duration Instruments': 'Otros',
    'Government Related': 'Government',
    'Municipal/Other': 'Government',
    'Banks & Brokers': 'Otros',
    'Other Financials': 'Otros',
    'Quasi, Sovereigns, Supranationals & Agencies': 'Otros',
    'Insurance': 'Financials',
    'Property': 'Real Estate',
    'Local Curr. Govt/Agency Bonds (Investment Grade)': 'Government',
    'Local Curr. Govt/Agency Bonds (Non Inv Grade)': 'Government',
    'Non-Local Curr. Sovereign Bonds (Non Inv Grade)': 'Government',
    'US Treasuries/Agencies': 'Otros',
    'Supranationals': 'Otros',
    'Non-Local Curr. Sovereign Bonds (Investment Grade)': 'Government',
    'Derivatives: Currency Derivatives': 'Otros',
    'Derivatives: Derivatives': 'Otros',
    'Telecommunications': 'Otros',
    'Financial Services': 'Otros',
    'Consumer Goods (Durable)': 'Main Consumer Goods',
    'Equipment Goods': 'Industrials',
    'Electricity & Technology': 'Otros',
    'Consumer Goods (Non Durables)': 'Consumer Discretionary',
    'Renewable Energy Technology': 'Energy',
    'Energy Storage & Infrastructure': 'Energy',
    'Industrial Efficiency': 'Industrials',
    'Automotive & Sustainable': 'Otros',
    'Derivatives & Cash': 'Otros',
    'Government': 'Government',
    'Corporates IG': 'Otros',
    'Agency Mortgage': 'Financials',
    'EMD Hard Currency': 'Otros',
    'Bonds (Covered)': 'Otros',
    'EMD Local Currency': 'Government',
    'Corporates HY': 'Otros',
    'Other Securitized': 'Otros',
    'Commercial Mortgage- Backed Securities': 'Financials',
    'IG Corp.': 'Otros',
    'Agency MBS': 'Otros',
    'EMD Local': 'Government',
    'Non-US HY Corp.': 'Otros',
    'US HY Corp.': 'Otros',
    'Convertible Bonds': 'Otros',
    'EMD Sovereign': 'Government',
    'Asset Backed Securities': 'Otros',
    'Non Agency MBS': 'Otros',
    'Corporates': 'Otros',
    'US Treasury': 'Otros',
    'Non-Agency Mortgage': 'Financials',
    'Non Corporate Credit': 'Financials',
    'US Agencies': 'Otros',
    'Financial Institutions': 'Otros',
    'Equities': 'Otros',
    'Agencies': 'Otros',
    'Oil & Gas': 'Energy',
    'Technology, Media & Telecommunications': 'Communication Services',
    'Consumer': 'Main Consumer Goods',
    'Real Estate': 'Real Estate',
    'Diversified': 'Otros',
    'Metals & Mining': 'Materials',
    'Infrastructure': 'Otros',
    'Basic Materials': 'Otros',
    'CDX': 'Otros',
    'Banks': 'Otros',
    'Net Liquid Assets': 'Otros',
    'Media': 'Communication Services',
    'Diversified Media': 'Communication Services',
    'Diversified Financial Services': 'Otros',
    'Cable & Satellite Television': 'Communication Services',
    'Super Retail': 'Consumer Discretionary',
    'Gas Distribution': 'Energy',
    'Real Estate / Homebuilders / Building Materials': 'Real Estate',
    'Consumer Products / Services': 'Main Consumer Goods',
    'Technology & Electronics': 'Otros',
    'Media - Cable': 'Communication Services',
    'Gaming / Lodging / Leisure': 'Consumer Discretionary',
    'High Yield': 'Otros',
    'Hard Currency (EM)': 'Otros',
    'Corporates (Investment Grade)': 'Otros',
    'Treasuries': 'Otros',
    'Collateralized Mortgage Obligations': 'Otros',
    'Collateralized Loan Obligations': 'Otros',
    'Residential Mtg Backed': 'Real Estate',
    'Commercial Mortgage Backed Securities': 'Financials',
    'Emerging Market Debt': 'Financials',
    'Mortgage Backed Securities': 'Financials',
    'Sovereigns (ex US)': 'Otros',
    'Commercial Papers & Notes': 'Otros',
    'Repos': 'Otros',
    'Bank Instruments': 'Financials',
    'Floating Rate Instruments': 'Otros',
    'Structured': 'Otros',
    'Telecommunication Services': 'Otros',
    'ACADEMIC & EDUCATIONAL SERVICES': 'Consumer Staples',
    'Leisure': 'Consumer Discretionary',
    'Consumer Goods': 'Main Consumer Goods',
    'External Sovereign Credit': 'Government',
    'High Yield Corporates': 'Otros',
    'US Equities': 'Otros',
    'Convertibles': 'Otros',
    'Corporate Bonds (Non Investment Grade)': 'Financials',
    'Government & Government Guaranteed Bonds': 'Government',
    'Municipal & Foreign City Bonds': 'Government',
    'Homebuilders & Real Estate': 'Real Estate',
    'Gaming': 'Consumer Discretionary',
    'Automobiles & Auto Parts': 'Industrials',
    'Chemicals': 'Otros',
    'Semiconductors & Semiconductor Equipment': 'Information Technology',
    'Software': 'Information Technology',
    'Interactive Media & Services': 'Communication Services',
    'Electronic Equip, Instrument & Components': 'Information Technology',
    'Broadline Retail': 'Consumer Discretionary',
    'Communications Equipment': 'Industrials',
    'Entertainment': 'Communication Services',
    'Technology Hardware, Storage & Peripherals': 'Information Technology',
    'Electrical Equipment': 'Industrials',
    'Integrated Oil': 'Energy',
    'Non Captive Consumer Finance': 'Main Consumer Goods',
    'Wireless': 'Communication Services',
    'Pipelines': 'Otros',
    'Media Cable': 'Communication Services',
    'Wirelines': 'Otros',
    'Mortgage Securities': 'Financials',
    'Euro Bonds': 'Otros',
    'Corporate Bonds': 'Financials',
    'Local': 'Government',
    'Credit Default Swaps': 'Financials',
    'Loan Securities': 'Financials',
    'Repurchase Agreements': 'Otros',
    'Discount Note': 'Otros',
    'Cash & Others': 'Otros',
    'Luxury': 'Consumer Discretionary',
    'Cosmetics': 'Otros',
    'Sport': 'Consumer Discretionary',
    'Travels': 'Otros',
    'Food and Drinks': 'Consumer Staples',
    'Water Technology': 'Utilities',
    'Environmental Services': 'Otros',
    'Water Supply': 'Utilities',
    'Derivatives': 'Otros',
    'Securitized Assets': 'Otros',
    'Global Credit (Investment Grade)': 'Financials',
    'Us Agencies': 'Otros',
    'Municipals Us': 'Otros',
    'Corporate': 'Financials',
    'Collateralized': 'Otros',
    'Finance': 'Otros',
    'Communication': 'Communication Services',
    'Covered': 'Otros',
    'Sovereigns': 'Otros',
    'Quasi & Foreign Government': 'Government',
    'Quasi Sovereigns': 'Otros',
    'Cash & Time Deposit': 'Otros',
    'Public Services': 'Government',
    'Capital Markets': 'Otros',
    'Consumer Finance': 'Main Consumer Goods',
    'Real Estate Management': 'Real Estate',
    'Municipals': 'Otros',
    'US Government Agencies': 'Government',
    'Pharmaceuticals': 'Otros',
    'Health Care Equip. & Supply': 'Health Care',
    'Biotechnology': 'Otros',
    'Health Care Providers & Services': 'Health Care',
    'Life Sciences Tools & Services': 'Otros',
    'Health Care Technology': 'Health Care',
    'Agency Mortgage Backed Securities': 'Financials',
    'Interest-Rate Derivatives': 'Otros',
    'Non-Local Currency Emerging Market Bonds': 'Government',
    'Residential Mortgage-Backed Securities': 'Real Estate',
    'Local Authorities': 'Government',
    'EM Hard Currency Corporate Debt': 'Financials',
    'EM Hard Currency Quasi Sovereign Debt': 'Government',
    'EM Hard Currency Sovereign Debt': 'Government',
    'DM Sovereign Debt': 'Government',
    'TELECOMMUNICATIONS SERVICES': 'Otros',
    'India': 'Otros',
    'Malaysia': 'Otros',
    'South Korea': 'Otros',
    'Indonesia': 'Otros',
    'Australia': 'Otros',
    'Kazakhstan': 'Otros',
    'Emerging Markets Government': 'Government',
    'EUR/UK Corporate': 'Financials',
    'US Corporates': 'Otros',
    'EUR/UK High Yield': 'Otros',
    'Local Emerging Market': 'Government',
    'US High Yield': 'Otros',
    'Emerging Market Corporate': 'Financials',
    'Corporate Bonds (Investment Grade)': 'Financials',
    'Corporate Bonds (Speculative Debt)': 'Financials',
    'Sovereign Bonds (Investment Grade)': 'Government',
    'Government & Agencies (Investment Grade)': 'Government',
    'Liquidities': 'Otros',
    'Sovereign Bonds (Speculative Debt)': 'Government',
    'Corporates (Industrials)': 'Otros',
    'Corporate - Financials': 'Financials',
    'Corporate - Utilities': 'Financials',
    'Building Materials': 'Industrials',
    'Containers': 'Otros',
    'Transportation (ex Air & Railway)': 'Industrials',
    'Other Industrials': 'Otros',
    'Local Government': 'Government',
    'Government Bonds': 'Government',
    'Electric Utilities': 'Utilities',
    'Unidentified': 'Otros',
    'Corporate (Investment Grade)': 'Financials',
    'Corporate (High Yield': 'Financials',
    'Emerging Markets - Investment Grade': 'Otros',
    'Government Bonds (Inflation Linked)': 'Government',
    'Municipal Bonds': 'Government',
    'Pass Through MBS': 'Otros',
    'Industrial': 'Industrials',
    'Investment Grade Credit': 'Financials',
    'Non-Agency Mortgage Backed Securities': 'Financials',
    'Collateralized Loan Obligation': 'Otros',
    'EM Local Currency': 'Government',
    'Emerging Markets Corporate': 'Financials',
    'Agency Residential Mortgage': 'Real Estate',
    'US Investment Grade Credit': 'Financials',
    'CLO Securities': 'Otros',
    'Commercial Mortgages': 'Otros',
    'US Interest Rate Derivatives': 'Otros',
    'US High Yield Credit': 'Financials',
    'Non-US Credit': 'Financials',
    'Home Builders & Real Estate': 'Real Estate',
    'Telecommunications Services': 'Otros',
    'EM Local Currency Sovereign Debt': 'Government',
    'EM Local Currency Corporate Debt': 'Government',
    'Hc Corp': 'Otros',
    'Quasi Government Debt': 'Government',
    'Cash & Derivatives': 'Otros',
    'Other': 'Otros',
    'Financials (Incl. Deposits)': 'Otros',
    'UCITS': 'Otros',
    'Gold': 'Materials',
    'Precious Metals & Minerals': 'Otros',
    'Silver': 'Materials',
    'Diversified Metals & Mining': 'Materials',
    'Exchange Traded Funds': 'Otros',
    'Liquidity': 'Otros',
    'Cyclical Services': 'Consumer Discretionary',
    'Financials & Investments': 'Otros',
    'Treasury & Govt. Related': 'Otros',
    'Automobiles': 'Otros',
    'Wired': 'Otros',
    'Treasury Bills': 'Otros',
    'Certificates of Deposit': 'Otros',
    'Consumer Services': 'Main Consumer Goods',
    'Sov Supra & Agency': 'Government',
    'Us Treasury': 'Otros',
    'Residential Mortgage Backed Securities': 'Real Estate',
    'Basic Trade': 'Otros',
    'Agency Arms': 'Otros',
    'Cable': 'Communication Services',
    'Packaging': 'Materials',
    'Financials & Investment Companies': 'Otros',
    'Electronics & Semiconductors': 'Otros',
    'Banks & Credit Institutions': 'Financials',
    'Internet Software & IT Services': 'Information Technology',
    'Energy & Water Supply': 'Energy',
    'Traffic & Transportation': 'Otros',
    'Pharmaceuticals, Cosmetics & Medical Products': 'Health Care',
    'Petroleum': 'Energy',
    'Emerging Markets Corporates': 'Otros',
    'Asset Back - / Mortgage Back Securities': 'Financials',
    'Other Securities': 'Otros',
    'Emerging Market Sovereigns': 'Otros',
    'Treasury': 'Otros',
    'Agency': 'Otros',
    'ABS': 'Otros',
    'Utility': 'Otros',
    'High Yield Corporate': 'Financials',
    'Bank Loans': 'Financials',
    'EM Local': 'Government',
    'Investment Grade': 'Otros',
    'EM External': 'Otros',
    'Covered Bonds and Mortgage Bonds': 'Financials',
    'Inflation Linked': 'Otros',
    'Retail': 'Consumer Discretionary',
    'China': 'Otros',
    'United States': 'Otros',
    'Hong Kong': 'Otros',
    'Japan': 'Otros',
    'Synthetic Cash': 'Otros',
    'Financial Company Commercial': 'Otros',
    'U.S. Government Agency R': 'Government',
    'Asset Backed Commercial': 'Otros',
    'Commercial Papers': 'Otros',
    'U.S. Treasury Debt': 'Financials',
    'Asset Backed Bonds': 'Otros',
    'Emerging Market Bonds': 'Otros',
    'Federal Governments Bonds': 'Otros',
    'Quasi Government Bonds': 'Government',
    'Treasury Repurchase Agreements': 'Otros',
    'Treasury Notes & Bills': 'Otros',
    'Availabilities & Invested Liquidities': 'Otros',
    'Suppliers': 'Otros',
    'Insight EMD Fund': 'Otros',
    'Corporate (Cyclical)': 'Consumer Discretionary',
    'Corporate (Non Cyclical)': 'Consumer Staples',
    'Cash & Other Assets Less Liabilities': 'Otros',
    'Unit Trusts': 'Otros',
    'Electric': 'Utilities',
    'Investment & Benefit Funds': 'Otros',
    'Non Credit': 'Financials',
    'Communications & Media': 'Communication Services',
    'Consumer Goods & Services (Non Cyclical)': 'Consumer Staples',
    'Electronics': 'Otros',
    'Natural Gas': 'Energy',
    'Automation': 'Otros',
    'Enabling Tech': 'Information Technology',
    'Consumer & Services Application': 'Main Consumer Goods',
    'Cash (Incl Futures)': 'Otros',
    'Reits': 'Otros',
    'Unclassified': 'Otros',
    'Government Debt (External)': 'Government',
    'HC Corp': 'Otros',
    'Local Government Debt': 'Government',
    'LC Corp': 'Otros',
    'Industry': 'Otros',
    'Mortgage Backed Security Pass-Through': 'Financials',
    'Government Related (Agencies)': 'Government',
    'Corporates (Financial Institutions)': 'Otros',
    'Government Related (Local Authority)': 'Government',
    'Government Related (Supranationals)': 'Government',
    'Corporate (Utilities)': 'Financials',
    'Government Related (Sovereign)': 'Government',
    'Residential Construction/Real Estate': 'Real Estate',
    'Miscellaneous Financial Services': 'Otros',
    'Metal/Mining': 'Materials',
    'Local Debt': 'Government',
    'Media & Entertainment': 'Communication Services',
    'Food': 'Consumer Staples',
    'Health Care & Pharmaceuticals': 'Health Care',
    'Metals': 'Otros',
    'Other Energy': 'Energy',
    'Retail REITs': 'Consumer Discretionary',
    'Health Care REITs': 'Health Care',
    'Residential REITs': 'Real Estate',
    'Real Estate Holding & Development': 'Real Estate',
    'Other Specialty Reits': 'Otros',
    'Industrial REITs': 'Industrials',
    'Storage Reits': 'Otros',
    'Diversified REITs': 'Otros',
    'Office REITs': 'Real Estate',
    'Home Construction': 'Industrials',
    'Public & Non Profit Institutions': 'Government',
    'Insurance Companies': 'Financials',
    'Health Care & Social Services': 'Health Care',
    'Supranational Organizations': 'Otros',
    'Computer Hardware & Network': 'Information Technology',
    'Non Agency RMBS': 'Otros',
    'Agency RMBS': 'Otros',
    'Treasuries & Treasury Futures': 'Otros',
    'Investment Grade Industrials': 'Otros',
    'Agency Pass-Through Mbs': 'Otros',
    'Investment Grade Financials': 'Otros',
    'Sovereign Related (ex Us)': 'Government',
    'Agency Debentures': 'Otros',
    'Not Classified': 'Otros',
    'Quasigovernment': 'Otros',
    'Governments': 'Otros',
    'Abs': 'Otros',
    'Municipalities': 'Otros',
    'Swaps': 'Otros',
    'Cable Operators': 'Communication Services',
    'Entertainment & Leisure': 'Communication Services',
    'Automotive': 'Otros',
    'Additional Tier 1': 'Financials',
    'Non-Financials': 'Otros',
    'Senior': 'Otros',
    'Tier 2': 'Financials',
    'Tier 1 & Preferred': 'Financials',
    'Tier 2 CoCo': 'Financials',
    'Duration Instruments Net Other Short': 'Otros',
    'Cash Deposits': 'Otros',
    'Mutual Funds': 'Otros',
    'Other Products': 'Otros',
    'Developed Market Sovereign': 'Government',
    'Local Currency Debt (EM)': 'Government',
    'FX': 'Otros',
    'Equity Funds': 'Financials',
    'Business Equipment & Services': 'Industrials',
    'Publishing': 'Otros',
    'Chemicals and Plastics': 'Otros',
    'Collateralized Mortgage Bonds': 'Otros',
    'Health Care Services': 'Health Care',
    'Oil & Gas Storage & Transportation': 'Energy',
    'Multi Utilities': 'Otros',
    'Telecom Tower Reits': 'Communication Services',
    'Gas Utilities': 'Energy',
    'Construction & Engineering': 'Industrials',
    'Airport Serv.': 'Industrials',
    'Water Utilities': 'Utilities',
    'Integrated Telecommunication': 'Otros',
    'Retail Transportation': 'Consumer Discretionary',
    'Euro High Yield': 'Otros',
    'Chemicals, Plastics & Rubber': 'Otros',
    'Hotels': 'Otros',
    'Health Care, Education & Childcare': 'Health Care',
    'Diversified & Conglomerate Services': 'Otros',
    'Broadcasting & Entertainment': 'Communication Services',
    'U.S. Govt & Agency Securities': 'Otros',
    'DM Government Agencies': 'Government',
    'EM Government Agencies': 'Government',
    'Mortgage Pass Thrus': 'Financials',
    'Inflation-Linked Inflation-Linked Securities': 'Otros',
    'Foreign Exchange': 'Otros',
    'Software & Services': 'Information Technology',
    'Technical Hardware & Equipment': 'Information Technology',
    'Canada': 'Otros',
    'Great Britain': 'Otros',
    'Germany': 'Otros',
    'Netherlands': 'Otros',
    'Italy': 'Otros',
    'Bermuda': 'Otros',
    'Foreign Sovereigns': 'Otros',
    'Commercial Mortgage Backed': 'Financials',
    'Quasi - Sovereigns': 'Otros',
    'Quasi - Corporates': 'Otros',
    'Non US Sovereigns': 'Otros',
    'High Grade Corporates': 'Otros',
    'Commercial MBS': 'Otros',
    'Mortgage Backed': 'Financials',
    'Non-Us Govt/Agency': 'Otros',
    'Lc Corp': 'Otros',
    'RMBS': 'Otros',
    'EM Corporate': 'Financials',
    'EM Government-Related': 'Government',
    'Insurance Linked Securities': 'Financials',
    'Gaming Lodging & Leisure': 'Consumer Discretionary',
    'Foreign Agencies': 'Otros',
    'Financial Institutions (Other)': 'Otros',
    'Life Insurance': 'Financials',
    'Other Reit': 'Real Estate',
    'Non Agency RMBS US': 'Otros',
    'RMBS (Non US)': 'Otros',
    'Pass-through (US Agency)': 'Otros',
    'CMBS (Non Us Agency)': 'Otros',
    'CMOs (US Agency)': 'Otros',
    'Absolute Return (US)': 'Otros',
    'CMBS (Non US)': 'Otros',
    'CMBS (Us Agency)': 'Otros',
    'FX & Cash': 'Otros',
    'Absolute Return (Non US)': 'Otros',
    'Staples Services': 'Otros',
    'Construction': 'Industrials',
    'Distribution': 'Otros',
    'Automobiles & Equipment suppliers': 'Industrials',
    'Media & Services': 'Communication Services',
    'Cable-Operators': 'Communication Services',
    'Related to Government Securities': 'Government',
    'Independent E&P': 'Otros',
    'Food & Beverage': 'Consumer Staples',
    'Hy Corporate': 'Financials',
    'EM Quasi & Sovereigns': 'Otros',
    'Ig Corporate': 'Financials',
    'Currencies': 'Otros',
    'Emerging Market Corporates': 'Otros',
    'Financial': 'Otros',
    'Sovereign': 'Government',
    'Consumer Non-Cyclical': 'Consumer Staples',
    'Consumer Cyclical': 'Consumer Discretionary',
    'Supranational': 'Otros',
    'Cash & Equivalent': 'Otros',
    'Pulp & Paper': 'Materials',
    'Physical Gold': 'Materials',
    'US Government': 'Government',
    'Bank Loan': 'Financials',
    'Enabling Technologies': 'Otros',
    'Energy Efficiency': 'Energy',
    'Renewables': 'Otros',
    'Enabling Infrastructure': 'Otros',
    'Residential': 'Real Estate',
    'Industrial Property': 'Real Estate',
    'Data Centers': 'Otros',
    'Retail Property': 'Real Estate',
    'Triple Net': 'Otros',
    'Office Space': 'Real Estate',
    'Sub Sovereign': 'Government',
    'Cash Equivalents': 'Otros',
    'Managed Health Care': 'Health Care',
    'Quasi': 'Otros',
    'Supranationales': 'Otros',
    'Floating Rate Notes': 'Otros',
    'Futures': 'Otros',
    'Forward Contracts': 'Otros',
    'Corporates (Financials)': 'Otros',
    'Non Corporates': 'Otros',
    'Corporates (Utilities)': 'Otros',
    'IT Security Products': 'Information Technology',
    'Security Services': 'Otros',
    'Physical Security Products': 'Otros',
    'Banking': 'Otros',
    'Consumer (Non Cyclical)': 'Consumer Staples',
    'Consumer (Cyclical)': 'Consumer Discretionary',
    'Technology & Electronic': 'Information Technology',
    'Finance & Investment': 'Otros',
    'Funds': 'Otros',
    'Support Services': 'Otros',
    'Construction/Communication/Lease Financing': 'Communication Services',
    'Specialty Retail': 'Consumer Discretionary',
    'Oil Refining & Marketing': 'Energy',
    'Investments & Misc Financial Services': 'Otros',
    'Air Transportation': 'Industrials',
    'Real Estate Investment Trusts': 'Real Estate',
    'Software & Serv.': 'Information Technology',
    'Health Services': 'Health Care',
    'Information Techn': 'Otros',
    'Communic Services': 'Otros',
    'Cash & Forwards': 'Otros',
    'Storage': 'Otros',
    'Apartments': 'Otros',
    'Data Center': 'Information Technology',
    'Retail, Other': 'Consumer Discretionary',
    'Free-Standing': 'Otros',
    'Strip Centers': 'Otros',
    'Enterprise': 'Otros',
    'Overnight & Repo': 'Otros',
    'Government & Agencies': 'Government',
    'Miscellaneous Consumer Goods': 'Main Consumer Goods',
    'Rails': 'Otros',
    'Toll Roads': 'Industrials',
    'Airports': 'Otros',
    'Gas': 'Energy',
    'Energy Infrastructure': 'Energy',
    'Water': 'Utilities',
    'Mortgage Pass Through': 'Otros',
    'Preferred Shares': 'Otros',
    'Agency Debenture': 'Otros',
    'Non-U.S. Treasury': 'Otros',
    'Emerging Market Hard Currency Debt': 'Financials',
    'Emerging Market Irs': 'Otros',
    'Supranational, Sub-Sovereign & Agency Paper': 'Materials',
    'Non Captive Diversified Finance': 'Otros',
    'Hospitals': 'Otros',
    'Industrial Development & Pollution Control Revenue': 'Industrials',
    'Dedicated Tax': 'Government',
    'Other Revenue': 'Otros',
    'Public Power': 'Utilities',
    'Higher Education': 'Consumer Staples',
    'Appropriation': 'Otros',
    'Commercial Paper/Cash': 'Materials',
    'Commercial Deposits': 'Otros',
    'Financial institutions': 'Otros',
    'TELECOMMUNICATION SERVICES-DISCONTINUED EFF 09/19/2020': 'Otros',
    'Term Deposits': 'Otros',
    'Liquid Assets': 'Otros',
    'Government Entities': 'Government',
    'Countries & Central Government': 'Government',
    'Mortgage & Funding Institutions': 'Financials',
    'Tobacco & Alcohol': 'Consumer Staples',
    'Quasi, Sovereign, Supranational & Agency': 'Government',
}
